### ISSUE TITLE
Reader-friendly preparation

### ISSUE THREAD

**Issue by shafr** [joeyhage/csslp-notes#1]
Hello, I'm also starting my preparation for CSSLP.

Can you please make small changes to your repo to have more reader-generator-friendly format ? 
I mean:
* move all documents under some top folder (notes?)
* add 1/2-digit prefix to top-level folders
* add digit to each mardkown from that folders ? 

I'll be able to create github action to generate documentation that you can serve on your github pages & that would be easier to read. (OR PDF for e-book reader)

Example:
https://github.com/shafr/CEH-in-bullet-points (source)
https://shafr.github.io/CEH-in-bullet-points/ (generated site)

**Comment by joeyhage** [comment]
@shafr sure! I can work on that over this weekend. I will let you know when done. Thanks for the suggestion!

**Comment by shafr** [comment]
thank you! Probably main concern is under specific chapter there are notes from different sources - im not sure if there is specific order or they just cover same topic but from few sides

**Comment by joeyhage** [comment]
@shafr I think I got it all done now. Not sure about some of the CSS/other formatting you may have on your CEH one but feel free to submit a PR :) 

https://joeyhage.github.io/csslp-notes/

**Comment by shafr** [comment]
No, that's it, everything looks great, only badge for some reason is not resolved to a link.
I started my own reading of `Essential CSSLP` today.

**Comment by joeyhage** [comment]
My notes are from the CSSLP Certification All-in-One Exam Guide. I take the exam one month from today so I will be adding a lot of review notes and other items before then.

**Comment by shafr** [comment]
Can you recommend any test sources ? 
Previously I used Sybex book for certification, 
not sure about what to use for CSSLP. (It seems like it's not so popular as CISSP)

**Comment by joeyhage** [comment]
For sample test questions? The All in One comes with an online code for McGraw-Hill which has sample test questions. It allows me to specify which chapters I want to generate a test for, how many questions, and then has optional hints as I take the test. For example, if I want a hint, it will first tell me which chapter/section of the book has the topic, then give a hint, then give the correct answer (before I finish the test exam). I got the book for about $50 and have found it very useful. That would be my main recommendation. 

Otherwise, I have other test sources through O’Reilly Online and Pluralsight (I have licenses for those two websites).

I have also found information on Reddit:

- https://reddit.com/r/CSSLP
- https://reddit.com/r/cybersecurity/search?q=CSSLP

**Comment by shafr** [comment]
After reading few hundred of pages (with a lot of stuff that I already knew & a lot of new terms and definitions that i didn't) I think that **mkdocs** are not the best choice for this cert preparation:
* I think it should be more `jekyll` style - where each article / entry has tags cloud which you can easily search through 
* and additionally there is chapter pages created where this snippets go one-by-one describing topics from different sources, so when you read through some specific item - it would show items related only to that topic

**Comment by shafr** [comment]
Here is what I meant (dirty example): 
https://shafr.github.io/csslp-notes-jekyll/tag-static
https://shafr.github.io/csslp-notes-jekyll/tag-collapse


https://github.com/shafr/csslp-notes-jekyll

**Comment by joeyhage** [comment]
Nice! I can see how that would help, too. I like the mkdocs format for my studying purposes so I’m not going to change it, but thanks for all the suggestions and good luck with your studying!
